config/routes.rb
Rails.application.routes.draw do
  resources :group_events do
    patch :published
  end

  root to: 'group_events#index'

  ## API ##
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :group_events do
        patch :published
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/serializable_resource.rb
module SerializableResource
  class MissingSerializable < StandardError; end

  def self.serialize(resource)
    return Array(resource).map(&:serialize) if resource.respond_to?(:to_ary)
    resource.serialize
  end

  def serialize
    serializable.as_jsonapi[:attributes]
  end

  def serializable
    unless serializable?
      raise MissingSerializable.new("Class not found: #{serializable_class_name}")
    end

    serializable_class.new(object: self)
  end

  def serializable?
    serializable_class_name.safe_constantize.present?
  end

  private

  def serializable_class
    serializable_class_name.constantize
  end

  def serializable_class_name
    # Note: this could be configurable if need be
    "Serializable#{self.class.name.demodulize}"
  end
end

app/models/group_event.rb
class GroupEvent < ApplicationRecord
  acts_as_paranoid
  include SerializableResource

  before_save :calculate_duration
  validate :validate_delete

  def calculate_duration
    self.duration = end_date - start_date if start_date && end_date
  end

  def calculate_duration_in_hours
    TimeDifference.between(start_date, end_date).humanize if start_date && end_date
  end

  def published_event
    update!(published: true) if all_fields_present?
  end

  def validate_delete
    errors.add(:general, 'cannot update delete records') if deleted?
  end

  private

  def all_fields_present?
    name.present? &&
      description.present? &&
      duration.present? &&
      location.present? &&
      start_date.present? &&
      end_date.present?
  end
end

app/controllers/api/v1/group_events_controller.rb
class Api::V1::GroupEventsController < GroupEventsController
  before_action :set_group_event, only: %i[show edit update destroy published]

  def index
    render json: GroupEvent.with_deleted.map(&:serialize)
  end

  def show
    render json: @group_event.serialize, status: 201
  end

  def new; end

  def create
    @group_event = GroupEvent.create!(group_event_params)
    render json: @group_event.serialize
  end

  def update
    @group_event.update(group_event_params)
    render json: @group_event.serialize
  end

  def published
    @group_event.published_event
    render json: @group_event.serialize
  end

  def destroy
    @group_event.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
  before_action :set_group_event, only: %i[show edit update destroy published]

  def index
    @group_events = GroupEvent.with_deleted
  end

  def show; end

  def new
    @group_event = GroupEvent.new
  end

  def edit; end

  def create
    @group_event = GroupEvent.new(group_event_params)

    respond_to do |format|
      if @group_event.save
        format.html { redirect_to @group_event, notice: 'Group event was successfully created.' }
        format.json { render :show, status: :created, location: @group_event }
      else
        format.html { render :new }
        format.json { render json: @group_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group_event.update(group_event_params)
        format.html { redirect_to @group_event, notice: 'Group event was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_event }
      else
        format.html { render :edit }
        format.json { render json: @group_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def published
    if @group_event.published_event
      flash[:success] = 'Group Event published!'
    else
      flash[:error] = 'All fields should be full!'
    end
    redirect_to @group_event
  end

  def destroy
    @group_event.destroy
    respond_to do |format|
      format.html { redirect_to group_events_url, notice: 'Group event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group_event
    @group_event = GroupEvent.with_deleted.find(params[:id] || params[:group_event_id])
  end

  def group_event_params
    params.require(:group_event).permit(:name, :description, :duration, :location, :end_date, :start_date, :number_days)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_events_helper.rb
module GroupEventsHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
  FLASH_TYPES = {
    'success' => 'success',
    'error' => 'danger',
    'alert' => 'warning',
    'notice' => 'info'
  }

  def bootstrap_class_for_flash(flash_type)
    FLASH_TYPES[flash_type] || flash_type.to_s
  end
end

app/views/group_events/_form.html.slim
.col-md-12
  = form_with(model: group_event, local: true) do |form|
    - if group_event.errors.any?
      ul
        - group_event.errors.full_messages.each do |message|
          li = message

    .form-group
      = form.label :name
      = form.text_field :name, id: :group_event_name, class: 'form-control'

    .form-group
      = form.label :number_days
      = form.number_field :number_days, id: :group_event_number_days, class: 'form-control'

    .form-group
      = form.label :description
      = form.text_area :description, id: :group_event_description, class: 'form-control froalaEditor'

    .form-group
      = form.label :location
      = form.text_field :location, id: :group_event_location, class: 'form-control'

    .form-group
      = form.label :start_date
      = form.text_field :start_date, id: :group_event_start_date, class: 'form-control datetimepicker-input', data: { toggle: 'datetimepicker', target: '#group_event_start_date', format: 'YYYY-MM-D H:mm:ss' }

    .form-group
      = form.label :end_date
      = form.text_field :end_date, id: :group_event_end_date, class: 'form-control datetimepicker-input', data: { toggle: 'datetimepicker', target: '#group_event_end_date' }

    = form.submit 'Update', class: 'btn btn-primary'
    a.btn.btn-light href='#{group_events_path}' Back

app/views/group_events/edit.html.slim
h1 Editing Group Event

= render 'form', group_event: @group_event

app/views/group_events/index.html.slim
h1 Group Events

table.table.table-bordered.table-hover.table-sm
  thead
    tr
      th Name
      th Start Date
      th End Date
      th Duration
      th Location
      th publish
      th
  tbody
    - @group_events.each do |group_event|
     tr
       td = group_event.name
       td = group_event&.start_date&.strftime("%F %T")
       td = group_event&.end_date&.strftime("%F %T")
       td = group_event.calculate_duration_in_hours
       td = group_event.location
       td = group_event.published
       td 
        - if !group_event.deleted?
          = link_to edit_group_event_path(group_event), class: 'btn btn-primary btn-sm', data: { turbolinks: "false" } do
              i.fa.fa-pencil
        | &nbsp;
        = link_to group_event_path(group_event), class: 'btn btn-primary btn-sm' do
            i.fa.fa-eye
        | &nbsp;
        - if !(group_event.published || group_event.deleted?)
          = link_to group_event_published_path(group_event), class: 'btn btn-warning btn-sm', method: 'patch' do
              i.fa.fa-calendar
        | &nbsp;
        - if !group_event.deleted?
          = link_to "/group_events/" + group_event.id.to_s, class: 'btn btn-danger btn-sm', method: 'delete', data: { confirm: 'Are you sure?' } do
              i.fa.fa-trash
        

= link_to 'New Group Event', new_group_event_path, class: 'btn btn-primary', data: { turbolinks: "false" }

app/views/group_events/new.html.slim
h1 New Group Event

= render 'form', group_event: @group_event

app/views/group_events/show.html.slim
.col-md-12
  h1 Group Event
    
  dl
    dt Name:
    dd #{@group_event.name}

    dt Start Date: 
    dd #{@group_event&.start_date&.strftime("%F %T")}

    dt End Date:
    dd #{@group_event&.end_date&.strftime("%F %T")}

    dt Duration:
    dd #{@group_event.calculate_duration_in_hours}

    dt Location:
    dd #{@group_event.location}

    dt Number days:
    dd #{@group_event.number_days}

    dt description:
    dd #{@group_event.description.html_safe}

    - if @group_event.published
        .card.text-white.bg-primary.mb-3 style="max-width: 18rem;"
          .card-header Event is published

    - if @group_event.deleted?
        .card.text-white.bg-danger.mb-3 style="max-width: 18rem;"
          .card-header Event Deleted!


= link_to 'Edit', edit_group_event_path(@group_event), class: 'btn btn-primary', data: { turbolinks: "false" }
| &nbsp;
= link_to 'Back', group_events_path, class: 'btn btn-light'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Group Events App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container-fluid'>
    <div class='container'>
      <%= render 'components/notification' %>
      <div class='row'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>